<!DOCTYPE html>

<html id="htmlSite">
<head>
	<meta http-equiv="Content-type" content="text/html;charset=utf-8">
	<meta name="author" content="Marc DESROSIERS, Amandine VANNIEUWERBURGH">

  <link rel="stylesheet" href="css/style.css">
	<link rel="stylesheet" href="css/div_md.css">
	<link rel="stylesheet" href="css/pages.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
  <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,700|Raleway:300,400,500,700|Dancing+Script">

<!--   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"> -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

  <title>La féérie du scrap</title>
  <link rel="icon" type="image/png" href="media_site/logo-petit.png" />
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-43495311-4', 'auto');
    ga('send', 'pageview');

  </script>

</head>
