
								
								<div id="banniereContent">
									<div id="banniere">
										<!--<img class="img_baniere" src="media_site/banngif.gif" height="180px">-->
											<div id="slideshow">
											    <ul id="sContent">
											    	<li><a href="#" target=""><img src="media_site/ban1.png" alt="Image bleue" class="imgBanniere"/></a></li>
											        <li><a href="#" target=""><img src="media_site/ban2.png" alt="Image verte" class="imgBanniere"/></a></li>
											        <li><a href="#"target=""><img src="media_site/ban3.png" alt="Image brune" class="imgBanniere" /></a></li>
											        <li><a href="#" target=""><img src="media_site/ban4.png" alt="Image brune" class="imgBanniere" /></a></li>
											        <li><a href="#" target=""><img src="media_site/ban5.png" alt="Image brune" class="imgBanniere" /></a></li>
											    </ul>
											</div>
			
									</div>
								</div>