<?php

	
//Test la valeur $POST

//substr($chaine, 0, 10); La fonction substr permet de récupérer le début de la chaine de caractère
//l'objectif est de sélectionner le début du texte : filters pour ensuite mettre à jour les talbes des filtres
?>

<!--	<div id='filtresArticles'>
		<form action="produits.php" method="post">
			<p>Stock</p>
			<div id='ativeFilters' class='filterZone'>
				<?php displayButtonFilters('filters_stock','idFiltersStock', 'nameFiltersStock')?>
			</div>
			<p>Prix</p>
			<div id='nonActiveFilters' class='filterZone'>
				<?php displayButtonFilters('filters_price','idPriceFilters', 'nameFiltersPrice')?>	
				
			</div>
			<p>Marques</p>
			<div id='nonActiveFilters' class='filterZone'>
				<?php displayButtonFilters('filters_brand','idFilters', 'nomMarques')?>		
			</div>
		</form>
	</div>
-->
	<div id='divArticlesArea'>
		<div id='divArticles'>

	