<?php include("payement-steps.inc");?>
<div class="payement-confirmation">
  <p><?php echo"$prenomClientSeul ";?>, merci pour votre commande sur Scrapdidi.</p>
  <p>Vous avez choisi de payer par virement bancaire.</p>
  <p>Pour procéder au virement, un email avec les coordonnées bancaires vous sera envoyé d’ici quelques minutes.</p>

  <p>Votre commande sera traitée dès réception du paiement.</p>

  <p>Merci de votre confiance et à bientôt.</p>
</div>
