<div class="payement-div">
  Payer par virement bancaire (le traitement de la commande sera plus long)
</div>
<div class="payement-div">
  Payer par chèque (le traitement de la commande sera plus long)
</div>
<div class="payement-div">
  Payez par carte ou par compte Paypal
</div>
<div class="payement-div">
  Paiement comptant au moment du retrait de votre commande à mon domicile ou sur salon
</div>
