<?php include("payement-steps.inc");?>
<div class="payement-confirmation">
  <p><?php echo"$prenomClientSeul ";?>, merci pour votre commande sur Scrapdidi.</p>
  <p>Vous avez choisi de payer par chèque bancaire.</p>
  <p>Pour procéder à l’envoi du chèque, un email avec l’ordre et l’adresse postale vous sera envoyé d’ici quelques minutes.</p>
  <p>Votre commande sera traitée après réception et encaissement du chèque.</p>
  <p>Merci de votre confiance et à bientôt.</p>
</div>
