<?php include("payement-steps.inc");?>
<div class="payement-confirmation">
  <p><?php echo"$prenomClientSeul ";?>, merci pour votre commande sur Scrapdidi.</p>
  <p>Vous avez choisi de retirer votre commande à mon domicile et de payer comptant à la livraison.</p>
  <p>Merci de me joindre sur mon portable au 06.75.20.58.66 afin de convenir d’un rendez-vous.</p>
  <p>Merci de votre confiance et à bientôt.</p>
</div>
